version: '3.9'

services:
  ruby:
    image: ruby:3.2.0
    container_name: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem

volumes:
  rubygems:
  gemconfig: